/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: jiayingc (https://sketchfab.com/jiayingc)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-cat-with-strawberries-769a5fa758de449e8154a6bbd33e9220
Title: Cute Cat with Strawberries
*/

import React from 'react'
import { useGLTF } from '@react-three/drei' 
// drei 라이브러리에서 useGLTF 훅을 가지고 옴
// 이 훅은 glTF 형식의 3D 모델을 로드하고 캐싱하여 사용할 수 있게 해 줌


export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
// scene.gltf 파일을 미리 로드하여 캐시에 저장
// 모델 렌더링하기 전 모델 파일을 미리 다운로드하려 성능 향상 가능

export default Model